In [3]:
import numpy as np

In [4]:
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [6]:
y = np.array

In [7]:
print(y)

<built-in function array>


In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.zeros(2)

array([0., 0.])

In [13]:
data1 = np.array([1,2,3,4,5])
data1

array([1, 2, 3, 4, 5])

In [15]:

pd.series(data1)

NameError: name 'pd' is not defined